import React, { useContext } from "react";
import Head from "next/head";
import styles from "./mainContainer.module.scss";
import ContainerContext from "../contexts/ContainerContext";
//
import Header from "./header";
import Main from "./main";

const MainContainer: React.FunctionComponent = () => {
    //
    const context = useContext(ContainerContext);
    const [open, setOpen] = context.open;
    //
    return (
        <div
            className={`{ ${styles.main_container} ${
                open ? styles.main_container_background : null
            }`}
        >
            <Head>
                <title>
                    Frontend Mentor | Intro section with dropdown navigation
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <Header />
            <Main />
        </div>
    );
};
export default MainContainer;
