import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.scss";
import Menu from "../svgs/icon-menu.svg";
import Close from "../svgs/icon-close-menu.svg";
import ArrowDown from "../svgs/icon-arrow-down.svg";
import ArrowUp from "../svgs/icon-arrow-up.svg";
import Todo from "../svgs/icon-todo.svg";
import Calendar from "../svgs/icon-calendar.svg";
import Reminders from "../svgs/icon-reminders.svg";
import Planning from "../svgs/icon-planning.svg";
export default function Home() {
    const [open, setOpen] = useState(false);
    const [featuresBox, setFeaturesBox] = useState(false);
    const [companyBox, setCompanyBox] = useState(false);
    return (
        <div
            className={`{ ${styles.main_container} ${
                open ? styles.main_container_background : null
            }`}
        >
            <Head>
                <title>
                    Frontend Mentor | Intro section with dropdown navigation
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <header className={styles.header}>
                <img src="/images/logo.svg" alt="company logo" />
                <button
                    type="button"
                    title="menu"
                    className={styles.hamburger_btn}
                    onClick={() => setOpen(!open)}
                >
                    {!open ? <Menu /> : <Close />}
                </button>
                <nav
                    className={`${styles.navigation} ${
                        open ? styles.navigation_mobile : null
                    }`}
                >
                    <div className={styles.dropdown_container}>
                        <a href="#">Features </a>
                        <button
                            type="button"
                            title="features"
                            className={styles.dropdown_btn}
                            onClick={() => setFeaturesBox(!featuresBox)}
                        >
                            {!featuresBox ? <ArrowDown /> : <ArrowUp />}
                        </button>
                        {featuresBox ? (
                            <div className={styles.dropdown_box}>
                                <div className={styles.wrapper}>
                                    <Todo />

                                    <p> Todo List</p>
                                </div>
                                <div className={styles.wrapper}>
                                    <Calendar />

                                    <p> Calendar</p>
                                </div>
                                <div className={styles.wrapper}>
                                    <Reminders />

                                    <p> Reminders</p>
                                </div>
                                <div className={styles.wrapper}>
                                    <Planning />

                                    <p>Planning</p>
                                </div>
                            </div>
                        ) : null}
                    </div>

                    <div className={styles.dropdown_container}>
                        <a href="#">Company</a>
                        <button
                            type="button"
                            title="company"
                            className={styles.dropdown_btn}
                            onClick={() => setCompanyBox(!companyBox)}
                        >
                            {!companyBox ? <ArrowDown /> : <ArrowUp />}
                        </button>
                        {companyBox ? (
                            <div
                                className={`${styles.dropdown_box} ${styles.dropdown_smaller_box}`}
                            >
                                <p> History</p>

                                <p> Our Team</p>

                                <p> Blog</p>
                            </div>
                        ) : null}
                    </div>

                    <a href="#">Careers</a>
                    <a href="#">About</a>
                </nav>
                <div className={styles.header_interaction}>
                    <button
                        type="button"
                        title="login"
                        className={styles.login_btn}
                    >
                        Login
                    </button>
                    <button
                        type="button"
                        title="Register"
                        className={styles.register_btn}
                    >
                        Register
                    </button>
                </div>
            </header>
            <main className={styles.main}>
                <picture className={styles.main_picture}>
                    <source
                        srcSet="/images/image-hero-desktop.png"
                        media="(min-width:1080px)"
                    ></source>
                    <img src="/images/image-hero-mobile.png" alt="" />
                </picture>
                <div className={styles.main_intro}>
                    <h1> Make remote work</h1>
                    <p>
                        Get your team in sync, no matter your location.
                        Streamline processes, create team rituals, and watch
                        productivity soar.
                    </p>
                    <a href="#" className={styles.learn_more}>
                        Learn more
                    </a>
                    <div className={styles.companies_logo_container}>
                        <img src="/images/client-databiz.svg" alt="" />
                        <img src="/images/client-audiophile.svg" alt="" />
                        <img src="/images/client-meet.svg" alt="" />
                        <img src="/images/client-maker.svg" alt="" />
                    </div>
                </div>
            </main>
        </div>
    );
}
